---
version: "3"

services:

  # --- MariaDB 10.3
  db:
    container_name: "project-db"
    image: bitnami/mariadb:10.3
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - project-db:/bitnami:delegated

  # --- PHP 7.3
  php:
    container_name: "project-php"
    image: bitnami/php-fpm:7.3
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - ./docker/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  # --- nginx 1.14
  nginx:
    container_name: "project-nginx"
    image: bitnami/nginx:1.14
    ports:
      - "80:8080"
    depends_on:
      - php
    volumes:
      - .:/app
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/vhosts/site.conf:ro

  # --- Redis 5.0
  redis:
    container_name: "project-redis"
    image: bitnami/redis:5.0
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  project-db:
    driver: local
