---
version: "3"

services:

  # --- MariaDB
  db:
    container_name: "${APP_NAME}-db"
    image: bitnami/mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_DATABASE}
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - project-db:/bitnami:delegated

  # --- PHP
  php:
    container_name: "${APP_NAME}-php"
    image: bitnami/php-fpm:8.0
    depends_on:
      - db
      - redis
    volumes:
      - .:/app:delegated
      - ./docker/php.ini:/opt/bitnami/php/etc/conf.d/php.ini:ro

  # --- nginx
  nginx:
    container_name: "${APP_NAME}-nginx"
    image: bitnami/nginx:1.21
    ports:
      - "80:8080"
    depends_on:
      - php
    volumes:
      - .:/app:delegated
      - ./docker/nginx.conf:/opt/bitnami/nginx/conf/server_blocks/site.conf:ro

  # --- Redis
  redis:
    container_name: "${APP_NAME}-redis"
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

volumes:
  project-db:
    driver: local
